DROP TABLE IF EXISTS Users BinSortData;

CREATE TABLE Users (
    Id INTEGER PRIMARY KEY,
    FirstName VARCHAR(64) NOT NULL, 
    LastName VARCHAR(64) NOT NULL,
    UserPassword VARCHAR(255) NOT NULL,
    IsTrainer BOOLEAN NOT NULL
);

CREATE TABLE BinSortData (
    Date TIMESTAMP NOT NULL,
    PartImage VARCHAR(255) NOT NULL, 
    Damages VARCHAR(255) NOT NULL,
    SystemDecision BOOLEAN NOT NULL,
    SorterDecision BOOLEAN NOT NULL,
    SorterId INTEGER FOREIGN KEY REFERENCES Users(ID) 
);